name: easy_pay
description: "Easy App customer app"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^6.0.3
  qr_code_scanner: ^1.0.0
  image_picker: ^1.1.2


  flutter_localizations:
    sdk: flutter
    
  url_launcher: ^6.1.10
  freezed_annotation: ^2.4.1
  dio: ^5.4.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/


